public class B2B_Constant {
 public static final STRING ACURA_VALUE = 'Acura';
 public static final STRING HONDA_VALUE = 'Honda';
 	public static final STRING SHIPPING_SPLIT = ',';
 	public static final STRING FAILURE_LABEL = 'FAILURE';
    public static final STRING WARNING_LABEL = 'WARNING';
    public static final STRING ERROR_LABEL = 'ERROR';
    public static final STRING DESCRIPTION = 'DESCRIPTION';
    public static final STRING SUCCESS = 'SUCCESS';
    public static final BOOLEAN TRUE_FLAG = TRUE;
    public static final BOOLEAN FALSE_FLAG = FALSE;
    public static final STRING USERNAME = 'username';
    public static final STRING FIRSTNAME = 'First Name';
   	public static final STRING LASTNAME = 'Last Name';
    public static final STRING EMAIL = 'Email';
    public static final STRING USERID = 'userId';
    public static final STRING PROFILENAME = 'Honda Sites User';
    public static final STRING DEFAULT_CARRIER_NAME = 'FEDEX';
    public static final STRING DEALER_RECORD_TYPE= 'Person Account';
    public static final STRING PREFERRED_FIELD_DELIVERY_TYPE = 'Preferred_Delivery_Type__c';
    public static final STRING NULL_VALUE = '';
    public static final STRING BUYER_STATUS='Active';
    
}