public class B2BConstants {
    public static final String SUCCESS = 'Success';
    public static final String INSTALL_AT_DEALER = 'Install At Dealer';
    //Added by shalini soni HDMP-5428 R2 Story
    public static final String ERROR = 'Error While Updating cart item';
    public static final String  PICK_AT_DEALER= 'Pick Up At Dealer';
    public static final String  ACCESSORY= 'Accessory';
     //Added by shalini soni HDMP-212 myDealers R2 Story
     public static final String  DEALER_NAME= 'Dealer';
    //End
}