/**
 * @description       :  
 * Update to use Named Credentials based
 * on current org.  This allows for 
 * easier development
 * @author          :  Erin Antonson
 * Email: eantonson@gorillagroup.com
 * @last modified on  : 01-10-2022
 * @last modified by  : eantonson@gorillagroup.com
**/
global class On_Sandbox_Creation implements SandboxPostCopy{
    
    global void runApexClass(SandboxContext context) {

    }
}